#' generatePCAPlots
#' @description generates PCA plot for each analytical platform
#' @author Ozlem Karadeniz \email{ozlem.karadeniz.283@@cranfield.ac.uk}
#' @param dataSet dataFrame from the data file generated by analytical platform
#' @param outputDir output directory name provided by the use in config json file
#' @param platform manalytical platform name
#' @import viridis shape
#'
#' @examples
#' \dontrun{generatePCAPlots(dataSet, outputDir, platform)}

generatePCAPlots <- function (dataSet, outputDir, platform) {

       if(file.exists(outputDir) == FALSE)
                dir.create(path = outputDir, showWarnings = FALSE)

        outputDir = paste0(outputDir, "/PCAPlots")
        if(file.exists(outputDir) == FALSE)
                dir.create(path = outputDir, showWarnings = FALSE)

        sam <- row.names(dataSet)
        varb <- colnames(dataSet)
        X <- as.matrix(dataSet)

        maxTVC <- max(dataSet$TVC)
        minTVC <- min(dataSet$TVC)

        #viridis colormap is used
        colors <- viridis((maxTVC - minTVC) * 100)

        colorsVector<-c()
        for (i in 1:nrow(dataSet)) {
                colorsVector[i] = colors[(dataSet$TVC[i] *100)- minTVC]
        }

        cat("\nAuto-scaled\n===========\n")
        aPCAMODEL <- prcomp(X,retx=T,center=T,scale=T)

        aSC <- aPCAMODEL$x
        aLD <- aPCAMODEL$rotation
        aEV <- aPCAMODEL$sdev^2

        outputFile = paste0(outputDir, "/" , platform, "_PCA.pdf")
        pdf(outputFile)

        ####x11()
        par(mar=c(5.1, 4.1, 4.1, 8.1), xpd=TRUE)
        plot(aSC[,1], aSC[,2], col=colorsVector, xlab="PC1", ylab="PC2", main="PCA score plot", type ="p")
        #shape::colorlegend(colors, c(seq(as.integer(minTVC), as.integer(maxTVC),1)), align="l", vertical=TRUE)
        shape::colorlegend(posx = c(0.8, 0.83), col = colorsVector,
                           zlim = c(minTVC, maxTVC), digit = 1)
        #legend("left", inset=c(1.2,1.1), legend="TVC", cex=0.8, col=colors, pch=1)
        #text(aSC[,1], aSC[,2], sam)

        dev.off()
}
