#' generatePCAPlots
#' @description generates PCA plot for each analytical platform
#' @author Ozlem Karadeniz \email{ozlem.karadeniz.283@@cranfield.ac.uk}
#' @param dataSet dataFrame from the data file generated by analytical platform
#' @param outputDir output directory name provided by the use in config json file
#' @param platform manalytical platform name
#' @import viridis shape ggplot2
#'
#' @examples
#' \dontrun{generatePCAPlots(dataSet, outputDir, platform)}

generatePCAPlots <- function (dataSet, outputDir, platform) {

       if(file.exists(outputDir) == FALSE)
                dir.create(path = outputDir, showWarnings = FALSE)

        outputDir = paste0(outputDir, "/PCAPlots")
        if(file.exists(outputDir) == FALSE)
                dir.create(path = outputDir, showWarnings = FALSE)

        # scaled <- mncn(dataSet[,-ncol(dataSet)])
        # scaled$TVC <- dataSet$TVC
        # dataSet<-scaled

        sam <- row.names(dataSet)
        varb <- colnames(dataSet)
        X <- as.matrix(dataSet)

        cat("\nAuto-scaled\n===========\n")
        aPCAMODEL <- prcomp(dataSet, scale. = TRUE)

        aSC <- aPCAMODEL$x
        aSC <- as.data.frame(aSC)
        aLD <- aPCAMODEL$rotation
        aEV <- aPCAMODEL$sdev^2

        #print(aPCAMODEL)

        # calculate % variance for first 3 PCs
        variance <- c(aEV[1] / sum(aEV) * 100,
                      aEV[2] / sum(aEV) * 100,
                      aEV[3] / sum(aEV) * 100)

        outputFile = paste0(outputDir, "/" , platform, "_PCA.pdf")
        pdf(outputFile)

        # p<-plot(aSC ,type = "scatter",x = ~PC1, y = ~PC2, text=rownames(aSC),
        #                mode="markers",
        #                marker=list(                size=11,
        #                                            color=dataSet$TVC,
        #                                            colorbar=list(
        #                                                    title='Colorbar'
        #                                            ),
        #                                            colorscale="Viridis",
        #                                            reversescale =T)
        #
        #                )%>%
        #         layout(title= paste0("PCA with ", platform,  " dataset coloured by TVC"),
        #                xaxis=list(title=sprintf("PC1 (%1.0f%%)", variance[1])),
        #                yaxis=list(title=sprintf("PC2 (%1.0f%%)", variance[2])))


        TVC <- dataSet$TVC
        p<-ggplot(aSC, aes(PC1, PC2))+
             geom_point(size = 4, aes(colour = TVC)) +
                xlab(sprintf("PC1 (%1.0f%%)", variance[1])) +
                ylab(sprintf("PC2 (%1.0f%%)", variance[2])) +
                labs(title=paste0("PCA with ", platform,  " dataset coloured by TVC"))+
                scale_color_viridis()+
                theme_bw()


        print(p)
        dev.off()
}


mncn <- function(X) {
        ndim <- dim(X)
        m = ndim[1]
        meanx <- apply(X,2,mean)
        ONE <- matrix(1,m,1)
        mx <- (X - (ONE %*% meanx))
        return(mx)
}

