#' generatePCAPlots
#' @description generates PCA plot for each analytical platform
#' @author Ozlem Karadeniz \email{ozlem.karadeniz.283@@cranfield.ac.uk}
#' @param dataSet dataFrame from the data file generated by analytical platform
#' @param outputDir output directory name provided by the use in config json file
#' @param platform manalytical platform name
#' @import colorRamps
#'
#' @examples
#' \dontrun{generatePCAPlots(dataSet, outputDir, platform)}

generatePCAPlots <- function (dataSet, outputDir, platform) {

       if(file.exists(outputDir) == FALSE)
                dir.create(path = outputDir, showWarnings = FALSE)

        outputDir = paste0(outputDir, "/PCAPlots")
        if(file.exists(outputDir) == FALSE)
                dir.create(path = outputDir, showWarnings = FALSE)

        datasetOrdered <- dataSet[order(dataSet$TVC),]

        X<-datasetOrdered
        sam <- row.names(X)
        varb <- colnames(X)
        X <- as.matrix(X)

        r <- nrow(datasetOrdered) %% 3
        n<- floor(nrow(datasetOrdered) / 3)
        r <- n-(3-r)
        colorPalette <- colorRampPalette(c("blue", "green", "red"))

        # use gradient to assign each class a different color
        colors <- colorPalette(3)
        categories<- rep(c(1, 2, 3), times = c(n, n, r))

        colorsVector<-c()
        for (i in 1:length(categories)) {
                #assign color depending on class
                colorsVector[i] = colors[categories[i]]
        }


        cat("\nAuto-scaled\n===========\n")
        aPCAMODEL <- prcomp(X,retx=T,center=T,scale=T)

        aSC <- aPCAMODEL$x
        aLD <- aPCAMODEL$rotation
        aEV <- aPCAMODEL$sdev^2

        outputFile = paste0(outputDir, "/" , platform, "_PCA.pdf")
        pdf(outputFile)

        ####x11()
        plot(aSC[,1], aSC[,2], col=colorsVector, xlab="PC1", ylab="PC2", main="PCA score plot")

        legend("topright", inset=c(-0.2,0), legend=c("low", "medium", "high"), cex=0.8, col=colors, pch=1)
        #text(aSC[,1], aSC[,2], sam)

        dev.off()
}
